"""Add plots table and link to diagnosis requests

Revision ID: 560d303625c7
Revises: 94f5be473704
Create Date: 2025-06-19 07:58:51.356835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560d303625c7'
down_revision: Union[str, Sequence[str], None] = '94f5be473704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('diagnosis_requests', sa.Column('plot_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'diagnosis_requests', 'plots', ['plot_id'], ['id'])
    op.drop_column('diagnosis_requests', 'plot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis_requests', sa.Column('plot', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'diagnosis_requests', type_='foreignkey')
    op.drop_column('diagnosis_requests', 'plot_id')
    op.drop_table('plots')
    # ### end Alembic commands ###
