"""Fix circular dependency on treatment plan

Revision ID: 94f5be473704
Revises: bff543f46bd3
Create Date: 2025-06-19 06:59:44.218836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f5be473704'
down_revision: Union[str, Sequence[str], None] = 'bff543f46bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('diagnosis_requests_treatment_plan_id_fkey'), 'diagnosis_requests', type_='foreignkey')
    op.drop_column('diagnosis_requests', 'treatment_plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis_requests', sa.Column('treatment_plan_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('diagnosis_requests_treatment_plan_id_fkey'), 'diagnosis_requests', 'treatment_plans', ['treatment_plan_id'], ['id'])
    # ### end Alembic commands ###
