"""Add treatment_plans table and relationship

Revision ID: f15fc6781ec4
Revises: 6b9c6a79e66a
Create Date: 2025-06-19 06:06:57.330184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f15fc6781ec4'
down_revision: Union[str, Sequence[str], None] = '6b9c6a79e66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('diagnosis_request_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_request_id'], ['diagnosis_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('diagnosis_requests', sa.Column('treatment_plan_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'diagnosis_requests', 'treatment_plans', ['treatment_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diagnosis_requests', type_='foreignkey')
    op.drop_column('diagnosis_requests', 'treatment_plan_id')
    op.drop_table('treatment_plans')
    # ### end Alembic commands ###
